server:
  port: 8880
  
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    #properties:
      #hibernate:
        #format_sql: true


  datasource:
    url: jdbc:h2:tcp://localhost/~/bigtong
    username: sa
    password:
    driver-class-name: org.h2.Driver

#logging:
  #level:
    #org.hibernate.SQL: debug
