server:
  port: 8880
  
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  datasource:
    url: jdbc:mysql://gogogo.ccszmnhxhmwx.ap-northeast-2.rds.amazonaws.com/gogogo_db
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

    #logging:
    #level:
    #org.hibernate.SQL: debug

